### ISSUE TITLE
Too many peer connections seen in chrome://webrtc-internals

### ISSUE THREAD

**Issue by zaidiqbalsoftech** [jamalag/mediasoup3#1]
**In a call with 10 participants there were around 100 peer connections seen in chrome://webrtc-internals**

I think this is because, on participant side for every producer a new receiverTransport is being created which creates a new peer connection, so if there are 10 participants in a call and all are producing then each participant will have 10 peer connections 1 for sending(senderTransport) and 9 for receiving(receiverTransport), hence total of 100 peer connections in a call of 10 participants, which created lots of processing burden on client side.

**This is same as peer-to-peer approach.**

To make it a full SFU we can create one sender transport and one receiver transport per participant and use that one receiver transport to consume multiple times to get media from all participants, then this should resolve the issue.

What do you say?

**Comment by jamalag** [comment]
I have not looked at the webrtc-internals but its a good point to do so.

My understanding is that each participant should have a total of 10 transport connections (1 producer, 9 consumers). In this case there is less burden on each participant in that only 1 upstream and 9 downstreams. 

When you mention 1 receiver transport, do you mean to pump all producers into one transport?

**Comment by zaidiqbalsoftech** [comment]
Yes 1 producer, 9 consumer per participant but 9 consumers should be attached to one single receiverTransport, that way there will be one peer connection with server to download streams per participant.

Each participant should create only 1 receiver transport or may be 2 depending upon the use case. If he creates 1 receiver transport per producer then this will be same as peer-to-peer approach. If there are 100 participants in call then there will be around 100 peer connections per participants on client side, client side will barely bear that much load.

I have not gone through the full documentation, I just watched your videos, but I have described it as per my understanding which I think is correct, kindly let me know thanks.

**Comment by jamalag** [comment]
I think I know what your mean in theory but I dont know how you would go about it. This is the process from producer (pcTransport, psTransport) to consumer (ccTransport, csTransport):

producer:
1. getVideoTrack() -> track
2. calls pcTransport.produce(track) -> raises on-connect and on-produce events
3. on-connect sends dtlsParams to Server which calls psTransport.connect({ dtlsParams })
4. on-produce sends kind, rtpParams, appData to Server which calls psTransport.produce( { kind, ... }) -> producer.id (pId)

Consumer:
1. sends request to Server to create csTransport -> returns Params: consumer.id (cId), iceParams, iceCandidates, dtlsParams
2. sends rtpCapabilities, pId, cId to Server and asks csTransport to consumer
3. Server returns pId, kind, rtpParams, cId
4. calls ccTransport.consume({ cId, pId, kind, rtpParams }) -> raises on-connect event
5. on-connect sends dtlsParams to Server which calls csTransport.connect({ dtlsParams })
6. call video track from consumer and add it to a video elements srcObject property

... and stream starts flowing.
Now imagine for each producer, you need to do the steps under the Consumer making sure you ref the cId.
I dont really know how mediasoup internally handles the added tracks to the only one stream. If you manage to do that, then you have to figure out (when you add audio tracks) which audio track belongs to which video track.

**Comment by jamalag** [comment]
> **In a call with 10 participants there were around 100 peer connections seen in chrome://webrtc-internals**
> 
> I think this is because, on participant side for every producer a new receiverTransport is being created which creates a new peer connection, so if there are 10 participants in a call and all are producing then each participant will have 10 peer connections 1 for sending(senderTransport) and 9 for receiving(receiverTransport), hence total of 100 peer connections in a call of 10 participants, which created lots of processing burden on client side.
> 
> **This is same as peer-to-peer approach.**
> 
> To make it a full SFU we can create one sender transport and one receiver transport per participant and use that one receiver transport to consume multiple times to get media from all participants, then this should resolve the issue.
> 
> What do you say?

I still haven't looked at webrtc-internals yet but I still don't get it. Is it that if I was a participant connected to mediasoup in a room with 9 other participants, I will see 100 connections on my side? I really have to check this. I know that as a participant from my end I should have 10 connections (1 up and 9 down)

However, I know for sure in a mesh topology from my end I will have 9 up and 9 down - where 9 up will bring my computer to a halt.

**Comment by zaidiqbalsoftech** [comment]
> > **In a call with 10 participants there were around 100 peer connections seen in chrome://webrtc-internals**
> > I think this is because, on participant side for every producer a new receiverTransport is being created which creates a new peer connection, so if there are 10 participants in a call and all are producing then each participant will have 10 peer connections 1 for sending(senderTransport) and 9 for receiving(receiverTransport), hence total of 100 peer connections in a call of 10 participants, which created lots of processing burden on client side.
> > **This is same as peer-to-peer approach.**
> > To make it a full SFU we can create one sender transport and one receiver transport per participant and use that one receiver transport to consume multiple times to get media from all participants, then this should resolve the issue.
> > What do you say?
> 
> I still haven't looked at webrtc-internals yet but I still don't get it yet. Is it that if I was a participant connected to mediasoup in a room with 9 other participants, I will see 100 connections on my side? I really have to check this. I know that as a participant from my end I should have 10 connections (1 up and 9 down)
> 
> However, I know for sure in a mesh topology from my end I will 9 up and 9 down - where 9 up will bring my computer to a halt.

In a call with 10 participants you will see 10 peer connections on your side 1 up and 9 down. But on server there will be 100 peer connections.

**Comment by zaidiqbalsoftech** [comment]
> I think I know what your mean in theory but I dont know how you would go about it. This is the process from producer (pcTransport, psTransport) to consumer (ccTransport, csTransport):
> 
> producer:
> 
> 1. getVideoTrack() -> track
> 2. calls pcTransport.produce(track) -> raises on-connect and on-produce events
> 3. on-connect sends dtlsParams to Server which calls psTransport.connect({ dtlsParams })
> 4. on-produce sends kind, rtpParams, appData to Server which calls psTransport.produce( { kind, ... }) -> producer.id (pId)
> 
> Consumer:
> 
> 1. sends request to Server to create csTransport -> returns Params: consumer.id (cId), iceParams, iceCandidates, dtlsParams
> 2. sends rtpCapabilities, pId, cId to Server and asks csTransport to consumer
> 3. Server returns pId, kind, rtpParams, cId
> 4. calls ccTransport.consume({ cId, pId, kind, rtpParams }) -> raises on-connect event
> 5. on-connect sends dtlsParams to Server which calls csTransport.connect({ dtlsParams })
> 6. call video track from consumer and add it to a video elements srcObject property
> 
> ... and stream starts flowing. Now imagine for each producer, you need to do the steps under the Consumer making sure you ref the cId. I dont really know how mediasoup internally handles the added tracks to the only one stream. If you manage to do that, then you have to figure out (when you add audio tracks) which audio track belongs to which video track.

I have actually manage to have only 2 peer connections 1 for up and 1 for down, and I consume all streams from that 1 down peer connection.

I create only one receiverTransport and then consume it multiple times as per the number of producers:
ccTransport.consume({ cId, pId, kind, rtpParams });

**Comment by jamalag** [comment]
> > > **In a call with 10 participants there were around 100 peer connections seen in chrome://webrtc-internals**
> > > I think this is because, on participant side for every producer a new receiverTransport is being created which creates a new peer connection, so if there are 10 participants in a call and all are producing then each participant will have 10 peer connections 1 for sending(senderTransport) and 9 for receiving(receiverTransport), hence total of 100 peer connections in a call of 10 participants, which created lots of processing burden on client side.
> > > **This is same as peer-to-peer approach.**
> > > To make it a full SFU we can create one sender transport and one receiver transport per participant and use that one receiver transport to consume multiple times to get media from all participants, then this should resolve the issue.
> > > What do you say?
> > 
> > 
> > I still haven't looked at webrtc-internals yet but I still don't get it yet. Is it that if I was a participant connected to mediasoup in a room with 9 other participants, I will see 100 connections on my side? I really have to check this. I know that as a participant from my end I should have 10 connections (1 up and 9 down)
> > However, I know for sure in a mesh topology from my end I will 9 up and 9 down - where 9 up will bring my computer to a halt.
> 
> In a call with 10 participants you will see 10 peer connections on your side 1 up and 9 down. But on server there will be 100 peer connections.

now i get it.

**Comment by jamalag** [comment]
> > I think I know what your mean in theory but I dont know how you would go about it. This is the process from producer (pcTransport, psTransport) to consumer (ccTransport, csTransport):
> > producer:
> > 
> > 1. getVideoTrack() -> track
> > 2. calls pcTransport.produce(track) -> raises on-connect and on-produce events
> > 3. on-connect sends dtlsParams to Server which calls psTransport.connect({ dtlsParams })
> > 4. on-produce sends kind, rtpParams, appData to Server which calls psTransport.produce( { kind, ... }) -> producer.id (pId)
> > 
> > Consumer:
> > 
> > 1. sends request to Server to create csTransport -> returns Params: consumer.id (cId), iceParams, iceCandidates, dtlsParams
> > 2. sends rtpCapabilities, pId, cId to Server and asks csTransport to consumer
> > 3. Server returns pId, kind, rtpParams, cId
> > 4. calls ccTransport.consume({ cId, pId, kind, rtpParams }) -> raises on-connect event
> > 5. on-connect sends dtlsParams to Server which calls csTransport.connect({ dtlsParams })
> > 6. call video track from consumer and add it to a video elements srcObject property
> > 
> > ... and stream starts flowing. Now imagine for each producer, you need to do the steps under the Consumer making sure you ref the cId. I dont really know how mediasoup internally handles the added tracks to the only one stream. If you manage to do that, then you have to figure out (when you add audio tracks) which audio track belongs to which video track.
> 
> I have actually manage to have only 2 peer connections 1 for up and 1 for down, and i consume all streams from that 1 down peer connection.
> 
> I create only one receiverTransport and then consume it multiple times as per the number of producers: ccTransport.consume({ cId, pId, kind, rtpParams });

That's interesting, I'd love to see you implementation.

**Comment by zaidiqbalsoftech** [comment]
I have noticed another thing, when I connect 3-4 other participants on localhost from another machine on the same network then video starts to lag. What can be the reason for this? 

My network is ok and I have restricted bitrate to 500kb for each stream so it is not choking my network, something else is happening.

Everything is ok if I try to join 10 times from same machine on localhost, problem comes when I join from another machine on same network

**Comment by zaidiqbalsoftech** [comment]
> > > I think I know what your mean in theory but I dont know how you would go about it. This is the process from producer (pcTransport, psTransport) to consumer (ccTransport, csTransport):
> > > producer:
> > > 
> > > 1. getVideoTrack() -> track
> > > 2. calls pcTransport.produce(track) -> raises on-connect and on-produce events
> > > 3. on-connect sends dtlsParams to Server which calls psTransport.connect({ dtlsParams })
> > > 4. on-produce sends kind, rtpParams, appData to Server which calls psTransport.produce( { kind, ... }) -> producer.id (pId)
> > > 
> > > Consumer:
> > > 
> > > 1. sends request to Server to create csTransport -> returns Params: consumer.id (cId), iceParams, iceCandidates, dtlsParams
> > > 2. sends rtpCapabilities, pId, cId to Server and asks csTransport to consumer
> > > 3. Server returns pId, kind, rtpParams, cId
> > > 4. calls ccTransport.consume({ cId, pId, kind, rtpParams }) -> raises on-connect event
> > > 5. on-connect sends dtlsParams to Server which calls csTransport.connect({ dtlsParams })
> > > 6. call video track from consumer and add it to a video elements srcObject property
> > > 
> > > ... and stream starts flowing. Now imagine for each producer, you need to do the steps under the Consumer making sure you ref the cId. I dont really know how mediasoup internally handles the added tracks to the only one stream. If you manage to do that, then you have to figure out (when you add audio tracks) which audio track belongs to which video track.
> > 
> > 
> > I have actually manage to have only 2 peer connections 1 for up and 1 for down, and i consume all streams from that 1 down peer connection.
> > I create only one receiverTransport and then consume it multiple times as per the number of producers: ccTransport.consume({ cId, pId, kind, rtpParams });
> 
> That's interesting, I'd love to see you implementation.

Here it is:

To save my time I have added a simple check on top of signalNewConsumerTransport method, if there is a consumer transport then use that one otherwise create it so it creates basically one time.

![image](https://user-images.githubusercontent.com/100468572/157087826-fed6a570-384e-452c-97dd-8a9b8b3002ef.png)

**Comment by jamalag** [comment]
great, I see you ensuring you create consumer transport only once.

**Comment by zaidiqbalsoftech** [comment]
> I have noticed another thing, when I connect 3-4 other participants on localhost from another machine on the same network then video starts to lag. What can be the reason for this?
> 
> My network is ok and I have restricted bitrate to 500kb for each stream so it is not choking my network, something else is happening.
> 
> Everything is ok if I try to join 10 times from same machine on localhost, problem comes when I join from another machine on same network

What can be the reason for this?

**Comment by jamalag** [comment]
> > I have noticed another thing, when I connect 3-4 other participants on localhost from another machine on the same network then video starts to lag. What can be the reason for this?
> > My network is ok and I have restricted bitrate to 500kb for each stream so it is not choking my network, something else is happening.
> > Everything is ok if I try to join 10 times from same machine on localhost, problem comes when I join from another machine on same network
> 
> What can be the reason for this?

Let me try to picture your setup: you have all the following on the same network ...
- machine running express server with mediasoup
- machine A
- machine B

when you connect 10 participants all from machine A, everything works ok
however, when you connect extra 3-4 participants from machine B, video starts to lag.

is the above correct or is it that mdeiasoup is running in machine A?

you got me confused when you mentioned 'localhost' on both machine A & B

**Comment by zaidiqbalsoftech** [comment]
'machine A' is my local machine, mediasoup is setup there and then there is another machine 'machine B', when I connect from machine A 10 times then all is well I think because it is on same network and uses host candidates for connection but when I connection 1 time from machine A and 4 times from machine B, the remote videos start lagging some get stuck.

It shouldn't be happening, I have been checking different things for past 2 days.

My network is all ok and working well.

**Comment by zaidiqbalsoftech** [comment]
Also I uploaded this demo on windows based aws server, installed everything there but remote video is not working for participants, just a black box. I have checked in webrtc-internals and found that candidates are not working, server is sending just host candidates and not srflx, prflx, relay candidates, peer connection doesn't get connected. I think it may be because of some listenIp, ports related issues.

ListenIp: server public address
announcedIp: null
rtcMinPort: 2000
rtcMaxPort: 2999

I have not opened these ports myself from server. Can you guide me if it is needed to open these ports if yes there from where I can do this?

**Comment by jamalag** [comment]
> Also I uploaded this demo on windows based aws server, installed everything there but remote video is not working for participants, just a black box. I have checked in webrtc-internals and found that candidates are not working, server is sending just host candidates and not srflx, prflx, relay candidates, peer connection doesn't get connected. I think it may be because of some listenIp, ports related issues.
> 
> ListenIp: server public address announcedIp: null rtcMinPort: 2000 rtcMaxPort: 2999
> 
> I have not opened these ports myself from server. Can you guide me if it is needed to open these ports if yes there from where I can do this?

With regards to video lagging, it's a bit difficult for me to tell, especially that you may have pumped all tracks into one consumer. If you may, pls share your code so that I can run it at me end and test. we can connect on LinkedIn, either I look you up or you look me up Name: AMIR ESHAQ.

With regards to ports, yes, you need to open those ports. Pls have a look at the doc under Running mediasoup in hosts with private IP (AWS, Google Cloud, Azure) ...
https://mediasoup.org/faq/#running-mediasoup-in-hosts-with-private-ip

and also this thread ...
https://mediasoup.discourse.group/t/difficulty-with-listen-ips-web-connection/1549/2

**Comment by zaidiqbalsoftech** [comment]
Thanks, I have attached my code here, kindly check. May be my machine A, on which mediasoup is running on localhost, has some network issue, everything works smooth if machine A is connected to LAN, not video quality issue but if I connect to wifi via tp-link then issue start even with 4 participants.

I have sent you connection request on linkedin, Zaid Iqbal.

[mediasoap-sfu-example.zip](https://github.com/jamalag/mediasoup3/files/8221006/mediasoap-sfu-example.zip)
.

**Comment by jamalag** [comment]
ok, I will try it out today and let you know

**Comment by zaidiqbalsoftech** [comment]
Thanks, I have tried today your original code again to see if my changed code is behaving this way and I have found that the original one work much better than my custom but still there were some video issues if I connect multiple times from same machine especially if I connect fourth time.

This issue here is reporting the same issue:
https://mediasoup.discourse.group/t/video-and-audio-lag-on-shared-internet-connection/1841

**Comment by jamalag** [comment]
If you are making multiple connections from the same machine then for sure you will notice not just video lagging but also your OS lagging - because you now have multiple clients each one trying to process the video to stream to the server.

**Comment by zaidiqbalsoftech** [comment]
Yes I was thinking about this plus network will be choking as well, to counter that I tested official mediasoup demo3 with different machines, we were around 10 people some were on network 1 and others were on network 2 but the call quality was not good. 

May be official demo server is of not that much capacity and may be their network is not that good so I will deploy it now to my server and test it there if all is well.

Have you tried mediasoup with around 20 people in call with video on? How was the quality at your end?

**Comment by zaidiqbalsoftech** [comment]
> ok, I will try it out today and let you know

Have you checked it?

**Comment by jamalag** [comment]
Sorry, I have been super busy the last few days. I hope to check it tomorrow.

**Comment by zaidiqbalsoftech** [comment]
Ok no problem, thanks.

**Comment by zaidiqbalsoftech** [comment]
After digging into it for 3 days I have come to a conclusion which is:

Things work smoothly if there is 1 receiver transport per stream(your original approach) but doesn't work well, video lags, if there is 1 receiver transport per client(mine approach). I have opened a thread on mediasoup discourse here:
https://mediasoup.discourse.group/t/1-receiver-transport-per-client-or-1-receiver-transport-per-stream/4019

**Comment by jamalag** [comment]
> > ok, I will try it out today and let you know
> 
> Have you checked it?

I tried it today; it seemed ok for the first few minutes, then started lagging slowly until all video elements went blank. At first I thought. well seems to work fine - connected 5 tabs on the mac machine running the server, connected another 4-5 from my windows machine, connected iPad, and 2 iPhones.

**Comment by zaidiqbalsoftech** [comment]
Yes this has been a headache for me for a whole week, but now I have come out of it as I mentioned here:

> After digging into it for 3 days I have come to a conclusion which is:
> 
> Things work smoothly if there is 1 receiver transport per stream(your original approach) but doesn't work well, video lags, if there is 1 receiver transport per client(mine approach). I have opened a thread on mediasoup discourse here: https://mediasoup.discourse.group/t/1-receiver-transport-per-client-or-1-receiver-transport-per-stream/4019

Thank you so much for your time, it has helped me a lot :)

**Comment by jamalag** [comment]
All the best bro!

**Comment by ishan501** [comment]
Hi, @zaidiqbalsoftech I've seen your below comment,

> The solution is to use 1 receiver transport per stream or 1 receiver transport for 2-5 streams may be e.g I use 1 receiver transport per remote person in call, 1 remote person’s camera stream and screen stream both are consumed on that 1 receiver transport. This gives best results.

Can you please share a part of that code?

**Comment by jamalag** [comment]
> Hi, @zaidiqbalsoftech I've seen your below comment,
> 
> > The solution is to use 1 receiver transport per stream or 1 receiver transport for 2-5 streams may be e.g I use 1 receiver transport per remote person in call, 1 remote person’s camera stream and screen stream both are consumed on that 1 receiver transport. This gives best results.
> 
> Can you please share a part of that code?

Ishan, Zaid has shared his code above on this thread https://github.com/jamalag/mediasoup3/issues/1#issuecomment-1063721348

**Comment by ishan501** [comment]
Hi, he has used it with a different method (1 receiver transport for all the streams). I wanted to know how he achieved 1 receiver transport for 2-5 streams (1 transport per client). Anyways, I've achieved it. Thank you!

**Comment by jamalag** [comment]
> Hi, he has used it with a different method (1 receiver transport for all the streams). I wanted to know how he achieved 1 receiver transport for 2-5 streams (1 transport per client). Anyways, I've achieved it. Thank you!

do you mean you achieved to combine multiple streams into one  consumer transport? if this is what you meant pls do a lot of tests as I am pretty sure there will be a performance degradation on the receiver client.

**Comment by ishan501** [comment]
Hi @jamalag, please check out his comment: https://mediasoup.discourse.group/t/1-receiver-transport-per-client-or-1-receiver-transport-per-stream/4019/10

Yes, I managed to combine audio and video streams into 1 consumer transport (per client).

So, for example, in your current implementation, you have 1 consumer transport per media stream. If the user is sharing both audio and video, you have 2 consumers transports. I managed to get that into 1. In my case, there will be a screen sharing stream also, so ideally there should be only 1 consumer transport per client.

Hoverer, I have not tested it yet. As per Zaidiq's comment, this approach is useful for him. @zaidiqbalsoftech Have you tested this approach?

**Comment by ishan501** [comment]
This is how I'm doing it, do you see any issues with this code? @jamalag @zaidiqbalsoftech 
![Screenshot 2022-04-11 152011](https://user-images.githubusercontent.com/29402999/162713458-ad1f8d03-669f-4792-830e-f2a078b251b4.png)

**Comment by jamalag** [comment]
> Hi @jamalag, please check out his comment: https://mediasoup.discourse.group/t/1-receiver-transport-per-client-or-1-receiver-transport-per-stream/4019/10
> 
> Yes, I managed to combine audio and video streams into 1 consumer transport (per client).
> 
> So, for example, in your current implementation, you have 1 consumer transport per media stream. If the user is sharing both audio and video, you have 2 consumers transports. I managed to get that into 1. In my case, there will be a screen sharing stream also, so ideally there should be only 1 consumer transport per client.
> 
> Hoverer, I have not tested it yet. As per Zaidiq's comment, this approach is useful for him. @zaidiqbalsoftech Have you tested this approach?

I think this way of limiting multiple streams from a single peer is better than combining many streams from many other peers. I quite agree with CosmosisT's comment where if you managed individual connections, then scaling is easier managed since you will be able to distribute them to other mediasoup servers. If you have a room with participant exceeding the max on a CPU Core, then you have no choice but to pipe your connection to another server.

CosmosisT's comment: https://mediasoup.discourse.group/t/1-receiver-transport-per-client-or-1-receiver-transport-per-stream/4019/2?u=jamalag

**Comment by jamalag** [comment]
HI Ishan, Ziad,
Would you like to connect on LinkedIn, may be we could may be video chat once in a while to discuss? let me know. I can be found on LinkedIn under name 'Amir Eshaq'.

**Comment by ishan501** [comment]
@jamalag For sure, this approach is better than just one consumer transport for all the streams. As Zaid has already implemented this, I'd like to know his test results.

@jamalag Let's connect. I'm not active on LinkedIn, you can find me on Skype: ishanshah501

**Comment by zaidiqbalsoftech** [comment]
@ishan501 I have tested **1 consumer transport per participant approach**, and it works really well no issues at all even on the same network. In my application I have 2 streams on one consumer transport, first one is camera video stream and second one is share screen stream, if any. We have been testing it in our application so far so good. In my view this is safe to implement you can go ahead with that.

You have max 3 streams per consumer transport which are audio, video , share screen. This is ok. 

**If you see any video lag related issue with 3 streams per consumer then you can surely move share screen to a new consumer transport but there will be no need of it as my test results suggest that it is safe to go with this approach.**

**Comment by zaidiqbalsoftech** [comment]
> HI Ishan, Ziad, Would you like to connect on LinkedIn, may be we could may be video chat once in a while to discuss? let me know. I can be found on LinkedIn under name 'Amir Eshaq'.

@jamalag you and I are connected on linkedin.

**Comment by zaidiqbalsoftech** [comment]
@ishan501 did you noticed the same video lag issue which I noticed with **all streams on one consumer transport** approach. If yes at how many participants video lag issue appeared on your side?

In my opinion this issue appears especially when you are connecting multiple participants on shared network, the video starts to lag. But with **1 consumer per participant** approach there is no video lag even on shared network.

Also make sure to open **UDP ports** when you deploy it to server if not call will work on **TCP** which can cause video lag again on shared network. Have spend plenty of my days on it :D

**Comment by ishan501** [comment]
Hi, @zaidiqbalsoftech. So, we have 3 cases,

1. One consumer transport for all the streams (most of the Mediasoup demos have this implemented)
2. One consumer transport per stream (as per this repo implementation)
3. One consumer transport per participant (as per your implementation)

I have not tested the 1st case myself, but as you are facing issues, I don't know why most of the demos have this implemented. Someone from the discourse thread is suggesting this way!

In the second case, I doubt if the system can/should handle all these nodes/connections for each stream. I successfully tested this approach with 25 participants. Started facing issues with 30.

For the third case, I'll have at most 4 streams per client: webcam, mic, screen video, and screen audio. Do you think I should use this approach instead? If yes, can you see my code attached above? 

I haven't found any official documentation on which is the correct way. It's all about R&D.

> Also make sure to open UDP ports when you deploy it to server if not call will work on TCP which can cause video lag again on shared network. Have spend plenty of my days on it :D

Do you mean the ports from RTC_MIN_PORT and RTC_MAX_PORT?

**Comment by zaidiqbalsoftech** [comment]
above mentioned approach 1) definitely causes issues.

2), 3) are both ok.

> In the second case, I doubt if the system can/should handle all these nodes/connections for each stream. I successfully tested this approach with 25 participants. Started facing issues with 30.

This will not be an issue, the actual thing which consumes CPU is not the number of connections itself but the number of streams going up and down. So using **1 transport per stream** or **1 transport per participant** should be same w.r.t CPU usage.

> For the third case, I'll have at most 4 streams per client: webcam, mic, screen video, and screen audio. Do you think I should use this approach instead? If yes, can you see my code attached above?

Yes I will go for this approach, have been using myself, have tested it for 2 stream but shouldn't cause issue for 3-4 streams as well. You may need to test it for 4 streams as per your use case. Why I go for this is that it is easier to manage the connection per client than per stream. If you leaves I know I need to close one connection something like that.

> I have not tested the 1st case myself, but as you are facing issues, I don't know why most of the demos have this implemented. Someone from the discourse thread is suggesting this way!

Yes I have read those threads as well, theoretically all streams on one connection shouldn't cause issue because there is no limitations on number of streams per connection as per webrtc docs but as per my test results this cause issues mentioned above.

**Producers should be all on one transport for better bandwidth handling.**

> Do you mean the ports from RTC_MIN_PORT and RTC_MAX_PORT?

Yes these ports should be open on server for public, call over UDP works really well than over TCP. So make sure you have these UDP ports open to public on your server.

**Comment by zaidiqbalsoftech** [comment]
I have edited my answers above, by '1 transport per client' I meant '1 transport per participant'. '1 transport per client' means that there is one transport for all streams. Needs to be corrected in your answers as well for future.

**Comment by jamalag** [comment]
> > HI Ishan, Ziad, Would you like to connect on LinkedIn, may be we could may be video chat once in a while to discuss? let me know. I can be found on LinkedIn under name 'Amir Eshaq'.
> 
> @jamalag you and I are connected on linkedin.

that's correct Zaid - I realized we just connected and not chat before. thanks

**Comment by ishan501** [comment]
Thank you so much for the details @zaidiqbalsoftech 
I've edited my answer.

**Comment by zaidiqbalsoftech** [comment]
My pleasure.
